### PR TITLE
Removed redundant import

### PR DESCRIPTION
**Pull request by mdunnio**

### CODE REVIEW

**Comment by wraithm** [comment]
What about older versions of GHC?

**Comment by mdunnio** [comment]
Just did some testing, and it looks like anything older than ghc 8.4.1 is broken.

**Comment by mdunnio** [comment]
I added some version bounds for backwards compatibility.

**Review by wraithm — APPROVED** [review]

**Comment by wraithm** [comment]
@lpsmith 

Any thoughts here? This seems pretty simple to me.

**Comment by lpsmith** [comment]
Seems ok to me

**Pull request merged**
